version: '3.5'

services:
  postgres:
    image: postgres:12
    container_name: postgresTechnicalTest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
      LISTEN_ADDRESSES: '*'
    volumes:
      - ./postgres-data/:/data/postgres/
      - "./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
    ports:
      - 5432:5432