spring:
  profiles:
    active: dev
  application:
    name: TarificationParkingApplicationService
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto:  update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test-db
    username: data&&Admin_User_test
    password: loua&&2019l
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  session:
    store-type: none

server:
  address: 0.0.0.0
  port: 8003


logging:
  pattern:
    console: " %d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n"
  level:
    com.numeryx: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    liquibase: INFO



